### ISSUE TITLE
Async requests handling

### ISSUE THREAD

**Issue by skliarovartem** [pixtron/binance-rate-limit#2]
Does it handle case when my code will call `checkMayDispatchRequest()` asynchronous, let's I start 1000 requests, before any `completeRequest()` is executed? Or I need to make all the requests synchronously one by one?

**Comment by pixtron** [comment]
You can still run multiple parallel request. Important is; if `checkMayDispatchRequest()` returns a value `>0` do not send the request, otherwise you will hit a rate limit. The value returned by `checkMayDispatchRequest()` is the milliseconds you should wait to retry this request. If you retry a request call `checkMayDispatchRequest()` again to 

if `limiter.checkMayDispatchRequest()` allows a request (return value 0) it will increase the `pendingUsage` usage in all relevant counters for a given request. So the counters can decide for further request if they still fit into the rate limits.
`limiter.completeRequest()` will then analyze the response headers and if the used weight returned from the server is higher update each counters current usage.

If you are close to the ip weight limits, `checkMayDispatchRequest()` might return a value >0 for a request with a high ip weight, but still return 0 for a request with a low ip weight.

If you want to log the current usage the limiter has a `getUsage()` method.

Hope this answer helps.

**Comment by skliarovartem** [comment]
Yes, thank you. It works! Do you have any plans to implement `fapi` besides `sapi`?

**Comment by pixtron** [comment]
I currently don't have the time to implement `fapi`. But a PR is always welcome.
As the limits on fapi look very similar to the ones in spot, it should probably doable with these 3. steps
1. copy the [spot config](https://github.com/pixtron/binance-rate-limit/blob/master/src/config/spot.ts) and adapt it to fapi
2. create the fapi limiter (copy and rename [spot limiter](https://github.com/pixtron/binance-rate-limit/tree/master/src/limiters))
3. create the fapi queue (copy and rename [spot queue](https://github.com/pixtron/binance-rate-limit/blob/master/src/queue/spot-queue.ts))

Not the spot limiter is only for `/api` endpoints. [The `/sapi` endpoints have limits for each single endpoint](https://binance-docs.github.io/apidocs/spot/en/#api-and-sapi-limit-introduction), whereas `/api` endpoints share the limits. According to docs `/fapi` works very similar to `/api`.

**Comment by skliarovartem** [comment]
BTW, I think it is still can go out and be blocked in parallel requests, because before we have response with the first request and count weights from headers, it can be second request and weights from the first request will not be counted

**Comment by skliarovartem** [comment]
> Not the spot limiter is only for /api endpoints. [The /sapi endpoints have limits for each single endpoint](https://binance-docs.github.io/apidocs/spot/en/#api-and-sapi-limit-introduction), whereas /api endpoints share the limits. According to docs /fapi works very similar to /api.

So your library is only for /api and doesn't implement /sapi rate limits?

**Comment by pixtron** [comment]
@skliarovartem 
> So your library is only for /api and doesn't implement /sapi rate limits?

correct. There is currently no plan on my side to implement `/sapi` as it has a custom rate limit that does not affect `/api`. But feel free to open a Pull Request to implements it.

> BTW, I think it is still can go out and be blocked in parallel requests, because before we have response with the first request and count weights from headers, it can be second request and weights from the first request will not be counted

It takes the `X-MBX-USED-WEIGHT-(intervalNum)(intervalLetter)` from the header, which is always the used weight in a given window. The window resets at the second 0 of the given interval. If the used weight in the header is smaller then the one tracked in the counter, the used weight from the counter is not overriden by the smaler used weight from the header.
